In [1]:
import numpy as np
import cv2

## Loading an Image - *cv2.imread()*

In [2]:
image = cv2.imread("opencv_logo.png")
print(type(image))
print(image)

<class 'numpy.ndarray'>
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


## Displaying an Image - *cv2.imshow()*

In [3]:
cv2.imshow("image", image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

## Checking dimensions of an Image - *np.shape*

In [4]:
dimensions = image.shape
print("\n Image Dimensions:", dimensions)


 Image Dimensions: (243, 207, 3)


## Loading an Image in grayscale

In [5]:
image_gray = cv2.imread("opencv_logo.png", 0)
dimensions = image_gray.shape
print("\n Image Dimensions:", dimensions)
cv2.imshow("image_gray", image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()


 Image Dimensions: (243, 207)


## Saving an Image - *cv2.imwrite()*

In [6]:
cv2.imwrite("opencv_logo_gray.png", image_gray)

True

## Accessing individual pixels

In [7]:
pixel_gray = image_gray[120, 120]
print("Pixel Color:", pixel_gray)
pixel_rgb = image[120, 120, :]
print("Pixel Color:", pixel_rgb)

Pixel Color: 29
Pixel Color: [255   1   1]


In [8]:
image[120, 120, : ] = [255, 255, 255]
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Accessing region of interest (ROI)

In [13]:
image[0:25, 0:25, :] = [0, 0, 0]
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Cropping an Image using Array slicing

In [14]:
image_cropped = image[0:205, 0:205, :]
cv2.imshow("cropped", image_cropped)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Checking out Individual Channels of an RGB Image

In [15]:
image_b_channel = image[:, :, 0]
image_g_channel = image[:, :, 1]
image_r_channel = image[:, :, 2]

cv2.imshow("image_b_channel", image_b_channel)
cv2.imshow("image_g_channel", image_g_channel)
cv2.imshow("image_r_channel", image_r_channel)
cv2.waitKey(0)
cv2.destroyAllWindows()